---
abstract: 'A FastCGI implementation of server interface to HTTP transport for XMLRPC::Lite'
author:
  - 'Six Apart <cpan@sixapart.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.132661'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XMLRPC-Transport-HTTP-FCGI
no_index:
  directory:
    - t
    - inc
requires:
  FCGI: 0
  Test::More: 0
  XMLRPC::Lite: 0
version: 0.01
